class_name CreatorWorkflow
extends RefCounted

const STATE_KEY := "creator_workflow_state"
const STATUS_KEY := "creator_package_status"
const HISTORY_KEY := "creator_submission_history"

func analyze(client: Node, idea_text: String, mode_id: String) -> Dictionary:
	var idea := _normalized_idea(idea_text)
	if idea.is_empty():
		return _failure("idea_required")
	var mode := _mode_record(mode_id)
	if mode.is_empty():
		return _failure("mode_not_found")
	if client == null:
		return _failure("online_client_missing", true)

	var discovery: Dictionary = await client.call(
		"discover_creator_keywords",
		idea,
		mode_id,
		_current_locale(),
		12
	)
	if not bool(discovery.get("ok", false)):
		return _response_failure(discovery)
	var discovery_data := discovery.get("data", {}) as Dictionary

	var registry: Dictionary = await client.call("fetch_creator_registry", {
		"kind": "capability",
		"mode_id": mode_id,
		"limit": 100
	})
	if not bool(registry.get("ok", false)):
		return _response_failure(registry)
	var registry_data := registry.get("data", {}) as Dictionary

	var game_id := _game_id(idea, mode_id)
	var manifest := {
		"schema_version": 2,
		"registry_revision": str(discovery_data.get(
			"revision",
			registry_data.get("revision", "")
		)),
		"game_id": game_id,
		"mode_id": mode_id,
		"interface": {
			"id": "interface.declarative_runtime",
			"version": "1.0.0",
			"required": true
		},
		"keywords": _keyword_ids(discovery_data),
		"capabilities": _capability_refs(registry_data),
		"assets": [],
		"entry": {
			"type": "declarative_v1",
			"path": "content/game.json"
		}
	}
	var resolution: Dictionary = await client.call("resolve_creator_manifest", manifest)
	if not bool(resolution.get("ok", false)):
		return _response_failure(resolution)
	var resolution_data := resolution.get("data", {}) as Dictionary
	var resolved := resolution_data.get("resolved_manifest", {}) as Dictionary
	if resolved.is_empty() or str(resolved.get("lock_digest", "")).is_empty():
		return _failure("manifest_resolution_empty")

	var save := _autoload("SaveSystem")
	if save == null:
		return _failure("save_system_missing")
	var state := {
		"game_id": game_id,
		"version": await _next_version(client, game_id),
		"idea": idea,
		"title": _title_from_idea(idea),
		"mode_id": mode_id,
		"mode": mode,
		"matches": discovery_data.get("matches", []),
		"resolved_manifest": resolved,
		"resolved_unix": int(Time.get_unix_time_from_system())
	}
	save.call("set_profile_value", STATE_KEY, state)
	save.call("set_profile_value", STATUS_KEY, {})
	save.call("set_profile_value", HISTORY_KEY, {})
	save.call("save_profile")
	return {"ok": true, "state": state}

func build_package() -> Dictionary:
	var state := load_state()
	var resolved := state.get("resolved_manifest", {}) as Dictionary
	if state.is_empty() or resolved.is_empty():
		return {}
	var meta := _package_meta(state)
	var definition := _definition(state)
	var payload := meta.duplicate(true)
	payload["resolved_manifest"] = resolved
	payload["files"] = [
		_file("meta.json", JSON.stringify(meta)),
		_file("creator_manifest.json", JSON.stringify(resolved)),
		_file("content/game.json", JSON.stringify(definition)),
		_file("README.md", "Declarative creator package generated by Creator Lab.")
	]
	return payload

func load_state() -> Dictionary:
	var save := _autoload("SaveSystem")
	var value: Variant = save.call("get_profile_value", STATE_KEY, {}) if save != null else {}
	return (value as Dictionary).duplicate(true) if typeof(value) == TYPE_DICTIONARY else {}

func current_game_id() -> String:
	return str(load_state().get("game_id", ""))

func has_resolved_state() -> bool:
	var state := load_state()
	return not (state.get("resolved_manifest", {}) as Dictionary).is_empty()

func _package_meta(state: Dictionary) -> Dictionary:
	var mode := state.get("mode", {}) as Dictionary
	var contract := _runtime_contract(mode)
	var title := str(state.get("title", "Creator Game"))
	return {
		"game_id": str(state.get("game_id", "")),
		"version": str(state.get("version", "0.1.0")),
		"author": _player_id(),
		"mode_id": str(state.get("mode_id", "")),
		"name": {"en": title, "ja": title, "zh-Hans": title},
		"min_players": int(mode.get("min_players", 1)),
		"max_players": int(mode.get("max_players", 1)),
		"tags": _package_tags(state),
		"requires_network": str(contract.get("network_profile", "")) != "offline_optional",
		"runtime_contract": contract,
		"entry_scene": "",
		"main_script": "",
		"asset_budget_bytes": int(
			_creator_modes().get("asset_budget_bytes", 5242880)
		)
	}

func _definition(state: Dictionary) -> Dictionary:
	var resolved := state.get("resolved_manifest", {}) as Dictionary
	var capabilities: Array[String] = []
	for value in resolved.get("capabilities", []):
		if typeof(value) == TYPE_DICTIONARY:
			capabilities.append(str((value as Dictionary).get("id", "")))
	return {
		"schema_version": 1,
		"game_id": str(state.get("game_id", "")),
		"mode_id": str(state.get("mode_id", "")),
		"type": _definition_type(str(state.get("mode_id", ""))),
		"title": str(state.get("title", "")),
		"keywords": resolved.get("keywords", []),
		"capabilities": capabilities,
		"settings": _default_settings(str(state.get("mode_id", "")))
	}

func _mode_record(mode_id: String) -> Dictionary:
	for value in _creator_modes().get("modes", []):
		if (
			typeof(value) == TYPE_DICTIONARY
			and str((value as Dictionary).get("id", "")) == mode_id
			and bool((value as Dictionary).get("public_runtime_enabled", false))
		):
			return (value as Dictionary).duplicate(true)
	return {}

func _runtime_contract(mode: Dictionary) -> Dictionary:
	return {
		"camera": str(mode.get("camera_key", "")).trim_prefix("creator.camera."),
		"input_profile": str(mode.get("input_key", "")).trim_prefix("creator.input."),
		"network_profile": str(mode.get("network_key", "")).trim_prefix("creator.network.")
	}

func _keyword_ids(discovery: Dictionary) -> Array[String]:
	var result: Array[String] = []
	for value in discovery.get("matches", []):
		if typeof(value) == TYPE_DICTIONARY:
			var keyword_id := str((value as Dictionary).get("id", ""))
			if not keyword_id.is_empty():
				result.append(keyword_id)
	return result

func _capability_refs(registry: Dictionary) -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	for value in registry.get("items", []):
		if typeof(value) != TYPE_DICTIONARY:
			continue
		var entry := value as Dictionary
		if str(entry.get("status", "")) in ["revoked", "deprecated"]:
			continue
		result.append({
			"id": str(entry.get("id", "")),
			"version": str(entry.get("version", "")),
			"required": true
		})
	return result

func _package_tags(state: Dictionary) -> Array[String]:
	var result: Array[String] = ["creator", str(state.get("mode_id", "creator"))]
	var resolved := state.get("resolved_manifest", {}) as Dictionary
	for value in resolved.get("keywords", []):
		var tag := str(value).get_slice(".", 2)
		if not tag.is_empty() and not result.has(tag):
			result.append(tag)
	return result.slice(0, 12)

func _game_id(idea: String, mode_id: String) -> String:
	var seed := "%s|%s|%s" % [_player_id(), mode_id, idea.to_lower()]
	return "creator_%s" % seed.sha256_text().substr(0, 20)

func _title_from_idea(idea: String) -> String:
	return idea.substr(0, mini(idea.length(), 48))

func _normalized_idea(value: String) -> String:
	return " ".join(value.replace("\n", " ").replace("\r", " ").split(" ", false)).strip_edges()

func _current_locale() -> String:
	var app := _autoload("App")
	if app != null:
		return str(app.get("current_locale"))
	return "en"

func _player_id() -> String:
	var save := _autoload("SaveSystem")
	return str(save.call("get_player_id")) if save != null else "creator_local"

func _creator_modes() -> Dictionary:
	var loader := _autoload("ConfigLoader")
	return loader.call("load_config", "creator_game_modes") as Dictionary if loader != null else {}

func _autoload(name: String) -> Node:
	var tree := Engine.get_main_loop() as SceneTree
	return tree.root.get_node_or_null(name) if tree != null else null

func _next_version(client: Node, game_id: String) -> String:
	var response: Dictionary = await client.call("fetch_creator_submission_history", game_id)
	if not bool(response.get("ok", false)):
		return "0.1.0"
	var best := Vector3i(0, 1, -1)
	for value in (response.get("data", {}) as Dictionary).get("items", []):
		if typeof(value) != TYPE_DICTIONARY:
			continue
		var parts := str((value as Dictionary).get("version", "")).split(".")
		if parts.size() < 3:
			continue
		var candidate := Vector3i(int(parts[0]), int(parts[1]), int(parts[2].get_slice("-", 0)))
		if _version_is_newer(candidate, best):
			best = candidate
	return "%d.%d.%d" % [best.x, best.y, best.z + 1]

func _version_is_newer(left: Vector3i, right: Vector3i) -> bool:
	if left.x != right.x:
		return left.x > right.x
	if left.y != right.y:
		return left.y > right.y
	return left.z > right.z

func _definition_type(_mode_id: String) -> String:
	return "tap_timing"

func _default_settings(mode_id: String) -> Dictionary:
	return {
		"duration_seconds": 60,
		"target_score": 12,
		"interaction": "tap",
		"difficulty": 1,
		"mode": mode_id
	}

func _file(path: String, content: String) -> Dictionary:
	return {
		"path": path,
		"size_bytes": content.to_utf8_buffer().size(),
		"content_text": content
	}

func _response_failure(response: Dictionary) -> Dictionary:
	return _failure(
		str(response.get("error", "request_failed")),
		bool(response.get("offline", false)) or int(response.get("status", 0)) == 0
	)

func _failure(error: String, offline: bool = false) -> Dictionary:
	return {"ok": false, "error": error, "offline": offline}
