class_name MessageTypes
extends RefCounted

const LOGIN := "login"
const AUTH_REFRESH := "auth.refresh"
const AUTH_FAILED := "auth.failed"
const CHAT_SEND := "chat.send"
const CHAT_HISTORY := "chat.history"
const CHAT_MESSAGE := "chat.message"
const EMOTE_SEND := "emote.send"
const EMOTE_EVENT := "emote.event"
const WORLD_JOIN := "world.join"
const WORLD_LEAVE := "world.leave"
const ROOM_DENIED := "room.denied"
const WORLD_SNAPSHOT := "world.snapshot"
const WORLD_DELTA := "world.delta"
const PLAYER_MOVE := "player.move"
const HOUSING_PLACE_ITEM := "housing.place_item"
const HOUSING_SAVE_LAYOUT := "housing.save_layout"
const HOUSING_LAYOUT_UPDATED := "housing.layout.updated"
const MINIGAME_JOIN := "minigame.join"
const MINIGAME_SESSION_CREATE := "minigame.session_create"
const MINIGAME_SESSION_JOIN := "minigame.session_join"
const MINIGAME_SESSION_LEAVE := "minigame.session_leave"
const MINIGAME_SESSION_END := "minigame.session_end"
const FISHING_CATCH := "fishing.catch"
const ECONOMY_GRANT_REWARD := "economy.grant_reward"
const ECONOMY_SPEND := "economy.spend"
const ECONOMY_LEDGER := "economy.ledger"
